### ISSUE TITLE
[Feature request] Hide backticks for inline code

### ISSUE THREAD

**Issue by masonc15** [mcndt/obsidian-quickshare#19]
Not sure if this is a feature request or a bug, but inline code syntax/highlighting _does_ use a different font but leaves the backticks in place when they should not appear.  See example below:

![FOVWW6r 1](https://user-images.githubusercontent.com/7069521/189497671-624aa0dc-2fa0-4c7f-bc46-f89d213e2aed.png)

It would be nice if the backticks were hidden and if the code could be shown as it is in Obsidian reading view.  Thanks.

**Comment by mcndt** [comment]
Thanks for letting me know! It's been fixed
