### ISSUE TITLE
[Bug] sidebar pane is navigable

### ISSUE THREAD

**Issue by kometenstaub** [mcndt/obsidian-quickshare#27]
**Describe the bug**

`navigation` on the sidebar pane should be set to false. Otherwise it takes focus. This has two implications. 

**To Reproduce**

1. Click on it, go back to the outline, it will not show the outline of the original file that was selected but nothing. The original file needs to be reselected.
2. Files can be opened in it when it is clicked (activated).

**Expected behavior**

It shouldn’t be navigable. 

**Environment (please complete the following information):**
 - OS: MacOS

**Additional context**

https://github.com/obsidianmd/obsidian-api/blob/38dd22168d2925086371bfc59e36fd9121527a39/obsidian.d.ts#L3845

https://github.com/mcndt/obsidian-quickshare/blob/184df12668b8a84ca429dbafbb3af7cd31fa43b6/src/ui/QuickShareSideView.ts#L6

**Comment by mcndt** [comment]
Fixed in 1.3.1!

**Comment by kometenstaub** [comment]
Thank you :)
