### ISSUE TITLE
Bug - 404 error on shareNote

### ISSUE THREAD

**Issue by jnes92** [mcndt/obsidian-quickshare#28]
Hey guys,
looks like an awesome plugin, but its not working for me.

```
Error: Request failed, status 404
    at new t (app.js:1:710073)
    at Aw (app.js:1:710265)
    at app.js:1:710942
    at app.js:1:235505
    at Object.next (app.js:1:235610)
    at a (app.js:1:234349)
```

Inside Func     `shareNote` I keep on getting inside the catch block `.catch(this.handleSharingError);` 
Title and body is looking good, seems like serverUrl is making some trouble? 

- I tried with various configurations inside plugin options, but It keeps failing
- I also created a new empty Vault without other plugins, does not work here, too :( 

Do you have any advice for me?

**Comment by mcndt** [comment]
Hey Jonas!

Thank you so much for bringing this to my attention. It looks like the note storage service was down, which is why you are receiving the 404.

I just rebooted it and it should be working!
