### ISSUE TITLE
[Bug] net::ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by JaPossert** [mcndt/obsidian-quickshare#49]
**Describe the bug**

I tried installing it through community plugins and BRAT but got this error in both cases:

net::ERR_CONNECTION_TIMED_OUT

**Environment (please complete the following information):**
 - OS: Windows11
- Surfuce Pro9

**Additional context**

**Comment by danielvartan** [comment]
Hey @JaPossert 

It was good while it lasted.

I found a new plugin that does the same thing. You can check it out here: https://github.com/alangrainger/share-note

Cheers!

**Comment by JaPossert** [comment]
Awesome! Thank you for sharing this 😃🙏👍

**Comment by mcndt** [comment]
Should be back up!
