### ISSUE TITLE
[Bug] Upload dies Not work anymore

### ISSUE THREAD

**Issue by kabokabeso** [mcndt/obsidian-quickshare#50]
**Describe the bug**
i loved your Plugin. But since a fiew Weeks i get The error Message „Request Failed.Could Not Connect to Server“, when I click create Share link. In settings “note share space” is enabled.

**To Reproduce**
- Describe the steps you took to reach this bug.

**Expected behavior**
Link with online file is created as it was the case some weeks ago. 

**Screenshots**
- Provide a screenshot showing what is wrong.
- If possible, share a note to noteshare.space and put the share link in this bug report so I can further debug the problem.

**Environment (please complete the following information):**
 - iPhone 14
 - Windows 11 
 - Obsidian up to date 

**Additional context**

**Comment by mcndt** [comment]
Should be back up!
